//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OceanicRoutePlanner.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Connection
    {
        public int Id { get; set; }
        public int Node1 { get; set; }
        public int Node2 { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> PlaneType { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual Location Location1 { get; set; }
        public virtual PlaneCapacity PlaneCapacity { get; set; }
    }
}
