//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OceanicRoutePlanner.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OceanicEntities : DbContext
    {
        public OceanicEntities()
            : base("name=OceanicEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<CategoryPrice> CategoryPrices { get; set; }
        public virtual DbSet<SizingRange> SizingRanges { get; set; }
        public virtual DbSet<SizingWeightPrice> SizingWeightPrices { get; set; }
        public virtual DbSet<WeightsRange> WeightsRanges { get; set; }
        public virtual DbSet<Connection> Connections { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<PlaneCapacity> PlaneCapacities { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserPermission> UserPermissions { get; set; }
    }
}
