//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OceanicRoutePlanner.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlaneCapacity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlaneCapacity()
        {
            this.Connections = new HashSet<Connection>();
        }
    
        public int Id { get; set; }
        public Nullable<decimal> MaxWidth { get; set; }
        public Nullable<decimal> MaxLenght { get; set; }
        public Nullable<decimal> MaxHeight { get; set; }
        public Nullable<decimal> MaxWeight { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Connection> Connections { get; set; }
    }
}
