//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OceanicRoutePlanner.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SizingRange
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SizingRange()
        {
            this.SizingWeightPrices = new HashSet<SizingWeightPrice>();
        }
    
        public int Id { get; set; }
        public Nullable<decimal> MaxHeight { get; set; }
        public Nullable<decimal> MaxDepth { get; set; }
        public Nullable<decimal> MaxBreadth { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SizingWeightPrice> SizingWeightPrices { get; set; }
    }
}
