//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OceanicRoutePlanner.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SizingWeightPrice
    {
        public int Id { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<int> Size { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual SizingRange SizingRange { get; set; }
        public virtual WeightsRange WeightsRange { get; set; }
    }
}
